# Generated by Django 6.0.2 on 2026-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
