# Generated by Django 6.0.2 on 2026-02-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('q1_has_degree', models.CharField(max_length=50)),
                ('q2_internship', models.CharField(max_length=50)),
                ('q3_mdcn_license', models.CharField(max_length=50)),
                ('q4_german_level', models.CharField(max_length=50)),
                ('q5_fsp_prep', models.CharField(max_length=50)),
                ('q6_experience_years', models.CharField(max_length=50)),
                ('q7_currently_practicing', models.CharField(max_length=50)),
                ('q8_funds', models.CharField(max_length=50)),
                ('q9_timeline', models.CharField(max_length=50)),
                ('q10_dependents', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
