# Generated by Django 5.1.6 on 2026-02-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eligibilityassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityassessment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gmailtoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('duration_hours', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='booking_payments/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='main.sessiontime')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
