# Generated by Django 6.0.2 on 2026-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
