# Generated by Django 6.0.2 on 2026-02-15 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'bmp', 'ico', 'pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'csv', 'ods', 'ppt', 'pptx', 'odp', 'mp3', 'wav', 'ogg', 'm4a', 'flac', 'mp4', 'mov', 'avi', 'mkv', 'wmv', 'webm'])])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Library',
                'ordering': ['-created_at'],
            },
        ),
    ]
